import {useState,type ReactNode} from 'react';
import {Copy,ExternalLink,LockKeyhole,MapPin} from 'lucide-react';
import {Avatar,Button,PrivacyBadge,short} from './components';
import {labels,type Profile} from './types';
export const shown=(profile:Profile,key:string)=>{const field=profile.fields[key];return field&&!field.locked&&typeof field.value==='string'?field.value:'';};
// Render the API result, never derive access from a selectable role or CSS.
export function ProfileView({profile,actions}:{profile:Profile;actions?:ReactNode}) {
  const [copied,setCopied]=useState('');const name=shown(profile,'displayName');
  async function copy(){try{if(navigator.clipboard){await navigator.clipboard.writeText(profile.did);setCopied('DID copied.');}else{setCopied('Select and copy the DID shown below.');}}catch{setCopied('Select and copy the DID shown below.');}}
  return <><section className="profile-hero"><div className="cover-art"><div className="cover-orbit" aria-hidden="true"/><span>SELF-SOVEREIGN SOCIAL</span></div><div className="profile-summary"><div className="profile-avatar-wrap"><Avatar large name={name}/></div><div className="profile-actions">{actions}</div><div className="profile-identity"><div className="name-row"><h1>{name||short(profile.owner)}</h1></div><button className="did-chip" type="button" onClick={copy} aria-label="Copy DID">{profile.did}<Copy size={14} aria-hidden="true"/></button><span role="status" className="copy-status">{copied}</span><p>{shown(profile,'bio')}</p>{shown(profile,'college')&&<div className="meta-row"><span><MapPin size={16} aria-hidden="true"/>{shown(profile,'college')}<PrivacyBadge level={profile.fields.college.visibility}/></span></div>}<div className="counts-row"><span><strong>{profile.posts.length}</strong> Posts</span><span><strong>{profile.followers.length}</strong> Followers</span><span><strong>{profile.following.length}</strong> Following</span></div><p className="viewer-result">{profile.isOwner?'Viewing as owner':profile.isFollower?'Viewing as follower':'Viewing public information'}</p></div></div></section><div className="profile-content"><section className="feed"><div className="about-card"><h2>Profile fields</h2>{Object.entries(profile.fields).map(([key,field])=><div className="about-field" key={key}><span>{labels[key]||key}</span><strong>{field.locked?<span className="restricted"><LockKeyhole size={14} aria-hidden="true"/>Restricted</span>:field.value||'Not set'}</strong><PrivacyBadge level={field.visibility}/></div>)}</div><section className="real-posts"><h2>Posts</h2>{profile.posts.length===0?<p>No posts yet.</p>:profile.posts.map(post=><article className="post-card" key={post.id}><header><Avatar name={name}/><div><strong>{name||short(profile.owner)}</strong><PrivacyBadge level={post.visibility}/></div></header><p>{post.locked?<span className="restricted"><LockKeyhole size={14} aria-hidden="true"/>Restricted post</span>:post.value}</p></article>)}</section></section><aside className="profile-aside"><div className="aside-card privacy-card"><span className="eyebrow">VISIBILITY</span><h3>Your profile, your boundaries.</h3><p>Fields shown here come from the authenticated profile service.</p><div className="visibility-key"><PrivacyBadge level="public"/><PrivacyBadge level="followers"/><PrivacyBadge level="private"/></div></div><div className="aside-card"><span className="eyebrow">PROFILE SOURCE</span><p>Chain {profile.chainId}</p><p className="mono">IPFS: {profile.cid}</p><details><summary>Follower wallets ({profile.followers.length})</summary>{profile.followers.map(wallet=><p className="mono" key={wallet}>{wallet}</p>)}</details><details><summary>Following wallets ({profile.following.length})</summary>{profile.following.map(wallet=><p className="mono" key={wallet}>{wallet}</p>)}</details></div></aside></div></>;
}
