import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router';
import {PenLine,Download} from 'lucide-react';
import {useAuth,Transaction} from '../shared/Auth';
import {Button,Empty,short} from '../shared/components';
import {ProfileView} from '../shared/ProfileView';
import type {Profile} from '../shared/types';
import {downloadReference,friendlyError} from '../../frontend/lib/client.js';
export function ProfileScreen({explore=false}:{explore?:boolean}) {
  const {client,ready,epoch,busy,run,setTx}=useAuth();const [params,setParams]=useSearchParams();
  const [query,setQuery]=useState(params.get('did')||''),[profile,setProfile]=useState<Profile|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[people,setPeople]=useState<any[]>([]);
  const target=explore?params.get('did')||'':client.address;
  useEffect(()=>{let active=true;setProfile(null);setError('');if(!ready||!target)return;setLoading(true);client.profile(target).then((p:Profile)=>{if(active)setProfile(p);}).catch((e:unknown)=>{if(!active)return;const msg=friendlyError(e);if(msg.includes('has not created')||msg.includes('No profile exists')||msg.includes('not created a profile yet')){setProfile(null);setError('');}else{setError(msg);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[client,ready,epoch,target]);
  useEffect(()=>{let active=true;if(ready&&explore)client.api('/profiles').then((r:any)=>{if(active)setPeople(r.profiles);}).catch((e:unknown)=>{if(active)setError(friendlyError(e));});return()=>{active=false;};},[client,ready,explore]);
  async function follow(){if(!profile)return;const token=client.token;const updated=await client.follow(profile.owner,profile.isFollower,(status:any)=>{if(client.token===token)setTx(status);});if(client.token===token)setProfile(updated);}
  return <div className="profile-page page-wrap">{explore&&<section className="lookup-panel"><span className="eyebrow">YOUR NETWORK</span><h1>Explore identities</h1><p>Resolve a wallet address or a did:pkh identity from this registry.</p><form className="search-box" onSubmit={e=>{e.preventDefault();setParams({did:query.trim()});}}><input className="input" aria-label="Wallet address or DID" value={query} onChange={e=>setQuery(e.target.value)} required/><Button type="submit" disabled={!ready||busy}>Load profile</Button></form><div className="people-list">{people.map(p=><Button key={p.owner} variant="secondary" onClick={()=>{setQuery(p.did);setParams({did:p.did});}}>{short(p.owner)}</Button>)}</div></section>}{loading&&<p role="status">Resolving profile…</p>}{error&&<p className="notice" role="alert">{error}</p>}{profile?<ProfileView profile={profile} actions={<>{profile.isOwner?<Link className="button button-secondary" to="/edit-profile"><PenLine size={17}/>Edit profile</Link>:client.address&&<Button disabled={busy} onClick={()=>run(follow)}>{profile.isFollower?'Unfollow':'Follow'}</Button>}<Button variant="ghost" disabled={busy} onClick={()=>downloadReference(client.export(profile))}><Download size={17}/>Export identity</Button></>}/>:!loading&&!explore&&!error&&<Empty title={client.address?'Create your identity':'Your identity starts here'}>{client.address?<Link className="button button-primary" to="/edit-profile">Create profile</Link>:'Connect MetaMask or a local demo wallet to open your profile.'}</Empty>}<Transaction/></div>;
}
